name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: mstorsjo/llvm-mingw:latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: libsdl-org/SDL
          path: sdl
      - uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          path: ffmpeg
      - name: build-sdl
        run: |
          mkdir local
          mkdir build
          cd build
          ../sdl/configure --host=aarch64-w64-mingw32 --prefix=${{ github.workspace }}/local
          make -j16
          make install
      - name: build ffmpeg
        run: |
          ln -s $PWD/build/sdl2-config $PWD/build/aarch64-w64-mingw32-sdl2-config
          chmod +x build/sdl2-config build/aarch64-w64-mingw32-sdl2-config
          export PATH=$PATH:$PWD/build
          cd ffmpeg
          echo $PATH
          aarch64-w64-mingw32-sdl2-config --version
          which aarch64-w64-mingw32-sdl2-config
          aarch64-w64-mingw32-sdl2-config --cflags
          ./configure --cross-prefix=aarch64-w64-mingw32- --arch=arm64 --target-os=mingw32 --enable-sdl --disable-doc || true
          # make -j16
          # ls
          tar cfz all.tar.gz ffmpeg sdl build local 
      - uses: actions/upload-artifact@v3
        with:
          path: all.tar.gz
