name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: mstorsjo/llvm-mingw:latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: libsdl-org/SDL
          path: sdl
      - uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          path: ffmpeg
      - name: build-sdl
        run: |
          mkdir -p ${{ github.workspace }}/local
          mkdir build
          cd build
          ../sdl/configure --host=aarch64-w64-mingw32 --prefix=${{ github.workspace }}/local
          make -j16
          make install
      - name: build ffmpeg
        run: |
          ln -s ${{ github.workspace }}/local/bin/sdl2-config ${{ github.workspace }}/local/bin/aarch64-w64-mingw32-sdl2-config
          chmod +x ${{ github.workspace }}/local/bin/sdl2-config ${{ github.workspace }}/local/bin/aarch64-w64-mingw32-sdl2-config
          export PATH=$PATH:${{ github.workspace }}/local/bin
          cd ffmpeg
          grep 0x020100 ./configure
          sed -i 's/0x020100/0x030000/' ./configure
          ./configure --cross-prefix=aarch64-w64-mingw32- --arch=arm64 --target-os=mingw32 --enable-sdl --disable-doc || true
          make -j16
      - name: archive
        run: |
          tar cfz all.tar.gz ffmpeg
      - uses: actions/upload-artifact@v3
        with:
          path: all.tar.gz
