name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: mstorsjo/llvm-mingw:latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: libsdl-org/SDL
          path: sdl
      - uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          path: ffmpeg
      - name: build-sdl
        run: |
          mkdir build
          cd build
          ../sdl/configure --host=aarch64-w64-mingw32
          make -j16
          make install
      - name: build ffmpeg
        run: |
          pkg_config --exists --print-errors "sdl2 >= 2.0.1 sdl2 < 3.0.0"
          ln -s build/sdl2-config build/aarch64-w64-mingw32-sdl2-config
          cat /usr/local/cross-tools/aarch64-w64-mingw32/lib/pkgconfig/sdl2.pc
          export PATH=$PATH:$PWD/build
          cd ffmpeg
          which aarch64-w64-mingw32-sdl2-config
          ./configure --cross-prefix=aarch64-w64-mingw32- --arch=arm64 --target-os=mingw32 --enable-sdl
          make -j16
          ls
